{"componentChunkName":"component---src-templates-type-history-tsx","path":"/history/class/statsGraphError","result":{"data":{"info":{"uid":"c_statsGraphError","type":"class","name":"statsGraphError","history":[{"action":"added","diff":"{\"name\":\"statsGraphError\",\"id\":3202127906,\"type\":\"StatsGraph\",\"arguments\":[{\"name\":\"error\",\"type\":\"string\"}],\"rawName\":\"statsGraphError\",\"namespace\":\"$root\",\"uid\":\"c_statsGraphError\",\"_type\":\"classes\"}","in":{"date":"27-03-2020","layer":111,"rev":0,"commit":"ed715fb8100f84ac328e9e022a43869a47da8b8e","file":"Telegram/Resources/tl/api.tl","website":null}}]},"object":{"prefix":"","type":"class","name":"statsGraphError","description":"<div>An error occurred while generating the <a href=\"https://core.telegram.org/api/stats\">statistics graph</a></div>\n","arguments":[{"name":"error","description":"<div>The error</div>\n"}]}},"pageContext":{"uid":"c_statsGraphError","name":"statsGraphError","type":"class"}},"staticQueryHashes":["3577901480"]}